version: '3.8'

services:
  db:
    image: postgres
    container_name: screenmatch-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alura_series
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data